### PR TITLE
Left Vs Right error for each spectral type

### PR DESCRIPTION
**Pull request by MeganMcAndie**

### CODE REVIEW

**Comment by krislars** [comment]
@MeganMcAndie and @hmchristenson, when can we meet for a hangouts meeting next week?  Let's talk about Megan's work in this new file.

**Comment by hmchristenson** [comment]
11am or 12pm Mon/Wed/Fri, 4pm Mon/Tues/Wed, 10am Tues/Thurs, 3pm Friday are the possibilities for me, I think.

**Comment by MeganMcAndie** [comment]
I'm free from 11-2 MWThF, anytime after 11am on Wednesday and after 3:30 everyday.

________________________________

**Comment by krislars** [comment]
Let's do 11 am on Wednesday.  Megan, let's meet in my office.  Holly, we'll meet you on Hangouts.  :)

**Comment by hmchristenson** [comment]
Sounds like a plan!

**Pull request merged**
